### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by AlexCuse** [jetheredge/SquishIt#309]
- [ ] kill 3.5 support (helps with #232)
- [ ] ajaxmin / yui upgrade (#261)
- [ ] preprocessor bootstrapping to work with VB (#232)
- [ ] cleanup temp files on shutdown

**Comment by AlexCuse** [comment]
probably may as well go .net 4.5 at this point

**Comment by leen3o** [comment]
Is there an ETA for v1?

**Comment by AlexCuse** [comment]
I'm hoping to have a beta release out after new years.  There's a lot of changes coming from 3.5 that I still need to make sense of, but I have some time over the next couple weeks.

**Comment by AlexCuse** [comment]
I just pushed a beta 1 release to nuget: https://www.nuget.org/packages/SquishIt/1.0.0-beta1

This breaks 3.5 support.

Also adds WebActivator as a reference, which should allow preprocessors to be self-registering and allow the framework assembly to clean up any temp files created when resolving embedded resources.

It also switches the default minifiers from AjaxMin to YUI - this change I might back out, not certain at this point.  

It also has a change that I guess I need to push to 0.9.8.1 that will create directories as needed for output files (inheriting from the parent folder permissions).  This eliminates the need to create all of your output folders on server prior to deployment.

**Comment by Worthaboutapig** [comment]
Do you have anyone to take up #315?  I'd be willing to look at it, using both SquishIt and Nancy and trying to get these running on Mono.

**Comment by AlexCuse** [comment]
I was starting to see that as a 1.1 feature, just because of my lack of experience w/ Nancy @worthaboutapig.  If you want to look at the Nancy side of things I can probably get you the necessary extensibility points this week though.  I looked at this when creating the issue and don't think it was too awful.  The main question I had was how best to deliver the aspnet specific bits, and whether or not a new nuget package would be necessary (I'd like to avoid that if possible, to minimize disruption)

**Comment by Worthaboutapig** [comment]
@AlexCuse I've made some comments on #315, but I'm happy to start as soon as you like.
